const SET_TOGGLED = "SET_TOGGLED";
const RESET_TOGGLED = "RESET_TOGGLED";
const CHANGE_EXAM_STATE = "CHANGE_EXAM_STATE";
const CHANGE_EXAM_TITLE = "CHANGE_EXAM_TITLE";
const CHANGE_QUESTION_TITLEID = "CHANGE_QUESTION_TITLEID";
const CHANGE_QUESTION_CONTENTID = "CHANGE_QUESTION_CONTENTID";
const CHANGE_QUESTION_OPTIONSID = "CHANGE_QUESTION_OPTIONSID";
const CHANGE_QUESTION_REQUIRE = "CHANGE_QUESTION_REQUIRE";
const CHANGE_EXAM_CHECKED = "CHANGE_EXAM_CHECKED";

const CHANGE_EXAM_TIME = "CHANGE_EXAM_TIME";
const CHANGE_EXAM_QUESTIONS = "CHANGE_EXAM_QUESTIONS";
const SAVE_EXAM = "SAVE_EXAM";
const SAVE_QUESTION = "SAVE_QUESTION";
const SAVE_MESSAGE = "SAVE_MESSAGE";
const SAVE_ANSWER = "SAVE_ANSWER";
const SAVE_ANSWER_TO_USER = "SAVE_ANSWER_TO_USER";
const SAVE_TEMP_QUESTION = "SAVE_TEMP_QUESTION";
const CLEAR_TEMP_QUESTION = "CLEAR_TEMP_QUESTION";

const GENE_EXAMID = "GENE_EXAMID";
const SET_CURRENTEXAM_ID = "SET_CURRENTEXAM_ID";
export {
  SET_TOGGLED,
  RESET_TOGGLED,
  SAVE_EXAM,
  CHANGE_EXAM_STATE,
  CHANGE_EXAM_TITLE,
  CHANGE_EXAM_QUESTIONS,
  CHANGE_QUESTION_CONTENTID,
  CHANGE_QUESTION_OPTIONSID,
  CHANGE_QUESTION_TITLEID,
  CHANGE_QUESTION_REQUIRE,
  SAVE_QUESTION,
  SAVE_MESSAGE,
  SAVE_ANSWER,
  SAVE_ANSWER_TO_USER,
  GENE_EXAMID,
  SET_CURRENTEXAM_ID,
  CHANGE_EXAM_TIME,
  CHANGE_EXAM_CHECKED,
  SAVE_TEMP_QUESTION,
  CLEAR_TEMP_QUESTION
};
