const SET_TOGGLED = 'SET_TOGGLED';
const RESET_TOGGLED = 'RESET_TOGGLED';
const CHANGE_EXAM_STATE = 'CHANGE_EXAM_STATE';
const CHANGE_EXAM_TITLE = 'CHANGE_EXAM_TITLE';
const CHANGE_QUESTION_TITLEID = 'CHANGE_QUESTION_TITLEID';
const CHANGE_QUESTION_CONTENTID = 'CHANGE_QUESTION_CONTENTID';
const CHANGE_QUESTION_OPTIONSID = 'CHANGE_QUESTION_OPTIONSID';

const CHANGE_EXAM_QUESTIONS = 'CHANGE_EXAM_QUESTIONS';
const SAVE_EXAM = 'SAVE_EXAM';
const SAVE_QUESTION = 'SAVE_QUESTION';
const SAVE_MESSAGE = 'SAVE_MESSAGE';

export {
  SET_TOGGLED,
  RESET_TOGGLED,
  SAVE_EXAM,
  CHANGE_EXAM_STATE,
  CHANGE_EXAM_TITLE,
  CHANGE_EXAM_QUESTIONS,
  CHANGE_QUESTION_CONTENTID,
  CHANGE_QUESTION_OPTIONSID,
  CHANGE_QUESTION_TITLEID,
  SAVE_QUESTION,
  SAVE_MESSAGE
};
