const ADD_QUESTION = "ADD_QUESTION";
const SELECT_DATE = "SELECT_DATE";
const CURRENT_EXAM = "CURRENT_EXAM";
const CONFIRM_MODAL = "CONFIRM_MODAL";
export { ADD_QUESTION, SELECT_DATE, CURRENT_EXAM, CONFIRM_MODAL };
