const ADD_QUESTION = "ADD_QUESTION";
const SELECT_DATE = "SELECT_DATE";
const CURRENT_EXAM = "SET_CURRENTEXAM";
const DELETE_MODAL = "DELETE_MODAL";
export { ADD_QUESTION, SELECT_DATE, CURRENT_EXAM, DELETE_MODAL };
